### ISSUE TITLE
Race condition after using proxmox role

### ISSUE THREAD

**Issue by gratuxri** [LinuxHaus/ansible_lihas_common#2]
`
TASK [lihas_common : Update apt cache] *************************************************************************************************************************************
fatal: [$IP]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://enterprise.proxmox.com/debian/pve/dists/buster/InRelease  401  Unauthorized [IP: 212.224.123.70 443], E:The repository 'https://enterprise.proxmox.com/debian/pve buster InRelease' is not signed."}
`

**Comment by areyer** [comment]
actually this only happens when the /etc/hosts is not correctly prepared for proxmox. You can do this by setting in your host_vars/myproxmoxhost.yml:
---
myproxmoxhost:
  config:
    hosts:
      "192.0.2.1":
        - myproxmoxhost.example.com
        - myproxmoxhost
